[config]
min_version = "0.32.4"
skip_core_tasks = true
default_to_workspace = true

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_WORKSPACE_SKIP_MEMBERS = [
    "examples/*",
]

[config.modify_core_tasks]
private = true
namespace = "core"

[tasks.check]
command = "cargo"
args = ["check"]
workspace = true

[tasks.clippy]
command = "cargo"
args = ["clippy", "--", "--deny=warnings"]
workspace = true

[tasks.test]
command = "cargo"
args = ["test", "--all-targets"]
workspace = true

[tasks.doc-test]
command = "cargo"
args = ["test", "--doc", "--all-features"]
workspace = true
